spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:thankoo-local;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
